// Biblioteca MP3 — Salsa, Vallenato, Merengue (Internet Archive, uso educativo escolar)
// Carátulas: portadas de cada colección en archive.org
window.MP3_LIBRARY = [
  { id: "s01", title: "Dakar, Punto Final", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/01%20Dakar%2C%20Punto%20Final.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s02", title: "La Juventud", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/02%20La%20Juventud.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s03", title: "Subway Joe", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/03%20Subway%20Joe.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s04", title: "Mercy Mercy Baby", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/04%20Mercy%20Mercy%20Baby.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s05", title: "Use It Before You Lose It", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/05%20Use%20It%20Before%20You%20Lose%20It.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s06", title: "The Hustler", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/06%20The%20Hustler.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s07", title: "Mambo De Bataan", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/07%20Mambo%20De%20Bataan.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s08", title: "Consolacion", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/08%20Consolacion.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s09", title: "Abran Paso", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/09%20Abran%20Paso.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s10", title: "Sonido Bestial", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/10%20Sonido%20Bestial.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s11", title: "Che Che Colé", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/11%20Che%20Che%20Col%C3%A9.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s12", title: "Anacaona", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/12%20Anacaona.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s13", title: "Quitate Tú (Live At The Cheetah)", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/13%20Quitate%20T%C3%BA%20(Live%20At%20The%20Cheetah).mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s14", title: "Pa' Bravo Yo", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/14%20Pa'%20Bravo%20Yo.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s15", title: "Asi Se Compone Un Son", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/15%20Asi%20Se%20Compone%20Un%20Son.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s16", title: "Indestructible", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/16%20Indestructible.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s17", title: "Calle Luna Calle Sol", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/17%20Calle%20Luna%20Calle%20Sol.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s18", title: "Que Se Sepa", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/18%20Que%20Se%20Sepa.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s19", title: "Coco Seco", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/19%20Coco%20Seco.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s20", title: "Quimbara", artist: "Salsa clásica", genre: "Salsa",
    mp3Url: "https://archive.org/download/salsacaliente/20%20Quimbara.mp3",
    cover: "https://archive.org/services/img/salsacaliente" },
  { id: "s21", title: "No morira", artist: "DLG", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/01.DLG%20-%20No%20morira.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s22", title: "Flaco Benitez", artist: "Tic tic tac", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/01.Flaco%20Benitez-%20Tic%20tic%20tac.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s23", title: "El sucusucu", artist: "Juan Valdes", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/01.Juan%20Valdes%20-%20El%20sucusucu.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s24", title: "La fuerza del corazon", artist: "Salsa unica", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/01.Salsa%20unica%20-%20La%20fuerza%20del%20corazon.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s25", title: "Grupomania", artist: "Linda eh", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/02.Grupomania-%20Linda%20eh.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s26", title: "Procuro olvidarte", artist: "Orquesta Palenque", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/02.Orquesta%20Palenque%20-%20Procuro%20olvidarte.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s27", title: "Mañana por la mañana", artist: "Rey Ruiz", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/02.Rey%20Ruiz%20-%20Ma%C3%B1ana%20por%20la%20ma%C3%B1ana.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s28", title: "Rumbera", artist: "Willy Chirino", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/02.Willy%20Chirino%20-%20Rumbera.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s29", title: "El Combo Dominicano", artist: "La botella", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/03.El%20Combo%20Dominicano-%20La%20botella.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s30", title: "Porque te amo", artist: "Nino Segarra", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/03.Nino%20Segarra%20-%20Porque%20te%20amo.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s31", title: "Procuro olvidarte", artist: "Raulin Rosendo", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/03.Raulin%20Rosendo%20-%20Procuro%20olvidarte.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s32", title: "Vereda tropical", artist: "Rey Ruiz", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/03.Rey%20Ruiz%20-%20Vereda%20tropical.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s33", title: "A que te pego mi mania", artist: "Grupomania", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/04.Grupomania%20-%20A%20que%20te%20pego%20mi%20mania.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s34", title: "Bailala pegaita", artist: "Hansel y Raul", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/04.Hansel%20y%20Raul%20-%20Bailala%20pegaita.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s35", title: "Que tiene ella", artist: "Mimi Ibarra", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/04.Mimi%20Ibarra%20-%20Que%20tiene%20ella.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s36", title: "Samba de Janeiro", artist: "Brazilia", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/05.Brazilia%20-%20Samba%20de%20Janeiro.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s37", title: "La mas sexy", artist: "Kaos", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/05.Kaos%20-%20La%20mas%20sexy.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s38", title: "Historia de un amor", artist: "Raulin Rosendo", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/05.Raulin%20Rosendo%20-%20Historia%20de%20un%20amor.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s39", title: "Estoy de tu parte", artist: "Tito Rojas", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/05.Tito%20Rojas%20-%20Estoy%20de%20tu%20parte.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s40", title: "Una aventura", artist: "Grupo Niche", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/06.Grupo%20Niche%20-%20Una%20aventura.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s41", title: "Mami, quien es mi papi", artist: "Juan Valdes", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/06.Juan%20Valdes%20-%20Mami%2C%20quien%20es%20mi%20papi.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s42", title: "Pa´ los que sufren", artist: "La Banda Gorda", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/06.La%20Banda%20Gorda%20-%20Pa%C2%B4%20los%20que%20sufren.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s43", title: "Pagina de amor", artist: "Tito Gomez", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/06.Tito%20Gomez%20-%20Pagina%20de%20amor.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s44", title: "Dile a el", artist: "Anthony Cruz", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/07.Anthony%20Cruz%20-%20Dile%20a%20el.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s45", title: "Volvamos a intentarlo", artist: "Mimi Ibarra", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/07.Mimi%20Ibarra%20-%20Volvamos%20a%20intentarlo.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s46", title: "Piano", artist: "Paquito Echevarria y Rey Ruiz", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/07.Paquito%20Echevarria%20y%20Rey%20Ruiz%20-%20Piano.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s47", title: "Juguete de nadie", artist: "Puerto Rican Power", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/07.Puerto%20Rican%20Power%20-%20Juguete%20de%20nadie.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s48", title: "Esa nena no me quiere", artist: "Karis", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/08.Karis%20-%20Esa%20nena%20no%20me%20quiere.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s49", title: "Subeme el radio", artist: "Lisa M.", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/08.Lisa%20M.%20-%20Subeme%20el%20radio.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "s50", title: "La fiesta ya se encendio", artist: "Los sabrosos del merengue", genre: "Salsa",
    mp3Url: "https://archive.org/download/los100mayoresexitosdelamusicasalsacdsrecopilatorios/08.Los%20sabrosos%20del%20merengue%20-%20La%20fiesta%20ya%20se%20encendio.mp3",
    cover: "https://archive.org/services/img/los100mayoresexitosdelamusicasalsacdsrecopilatorios" },
  { id: "v01", title: "AMIGO EL CORAZON", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/AMIGO%20EL%20CORAZON%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201997.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v02", title: "Acuerdate de mi", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Acuerdate%20de%20mi%20-%20Binomio%20De%20Oro%20De%20America%20-%202000.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v03", title: "BAÑARTE EN MIS SUEÑOS", artist: "BINOMIO DE ORO DE AMERICA (Carlos Arturo Brito) 1996", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/BA%C3%91ARTE%20EN%20MIS%20SUE%C3%91OS%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20(Carlos%20Arturo%20Brito)%201996.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v04", title: "CELOS", artist: "BINIOMIO DE ORO DE AMERICA (Fabian Corrales) 1994", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/CELOS%20-%20BINIOMIO%20DE%20ORO%20DE%20AMERICA%20(Fabian%20Corrales)%201994.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v05", title: "CHUCURRUCUCHU", artist: "BINOMIO DE ORO DE AMERICA (Israel Romero - Fidel Corzo) 1995", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/CHUCURRUCUCHU%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20(Israel%20Romero%20-%20Fidel%20Corzo)%201995.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v06", title: "CIEN AÑOS DE AUSENCIA", artist: "MIGUEL MORALES (Rafael Manjarres) 1993", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/CIEN%20A%C3%91OS%20DE%20AUSENCIA%20-%20MIGUEL%20MORALES%20(Rafael%20Manjarres)%201993.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v07", title: "COMO TE OLVIDO", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/COMO%20TE%20OLVIDO%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201996.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v08", title: "Canto al amor", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Canto%20al%20amor%20-%20Binomio%20De%20Oro%20De%20America%20-%201998.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v09", title: "Como expresar lo que siento (Israel David Romero)", artist: "Binomio de Oro de America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Como%20expresar%20lo%20que%20siento%20(Israel%20David%20Romero)%20-%20Binomio%20de%20Oro%20de%20America%20-%202003.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v10", title: "Como negar tus besos", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Como%20negar%20tus%20besos%20-%20Binomio%20De%20Oro%20De%20America%20-%201995.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v11", title: "Como olvidarte (Gabriel Arregoces)", artist: "Binomio de Oro de America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Como%20olvidarte%20(Gabriel%20Arregoces)%20-%20Binomio%20de%20Oro%20de%20America%20-%202003.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v12", title: "Como vamos a quedar", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Como%20vamos%20a%20quedar%20-%20Binomio%20De%20Oro%20De%20America%20-%201999.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v13", title: "Corazoncito negro", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Corazoncito%20negro%20-%20Binomio%20De%20Oro%20De%20America%20-%202001.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v14", title: "Cuando Vuelvas (Jean Carlos Centeno)", artist: "Binomio de Oro de America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Cuando%20Vuelvas%20(Jean%20Carlos%20Centeno)%20-%20Binomio%20de%20Oro%20de%20America%20-%202003.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v15", title: "DIFICIL DE IGUALAR", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/DIFICIL%20DE%20IGUALAR%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%202000.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v16", title: "DIME COMO TE OLVIDO", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/DIME%20COMO%20TE%20OLVIDO%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%202001.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v17", title: "DIME QUIEN", artist: "BINOMIO DE ORO DE AMERICA, Canta Gaby Garcia", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/DIME%20QUIEN%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%2C%20Canta%20Gaby%20Garcia%20-%201993.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v18", title: "DISTINTOS DESTINOS", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/DISTINTOS%20DESTINOS%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201997.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v19", title: "Dejame acercarme a ti (Nirlon Sanchez)", artist: "Binomio de Oro de America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Dejame%20acercarme%20a%20ti%20(Nirlon%20Sanchez)%20-%20Binomio%20de%20Oro%20de%20America%20-%202003.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v20", title: "Dejate atrapar", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Dejate%20atrapar%20-%20Binomio%20De%20Oro%20De%20America%20-%202000.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v21", title: "EL AMOR", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/EL%20AMOR%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201998.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v22", title: "El forastero", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/El%20forastero%20-%20Binomio%20De%20Oro%20De%20America%20-%201995.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v23", title: "GRAFITI DE AMOR", artist: "BINOMIO DE ORO DE AMERICA (Jhon Gonzalez) 2005", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/GRAFITI%20DE%20AMOR%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20(Jhon%20Gonzalez)%202005.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v24", title: "Hoy me di cuenta", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Hoy%20me%20di%20cuenta%20-%20Binomio%20De%20Oro%20De%20America%20-%201997.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v25", title: "Impredecible (Alejandro Palacio)", artist: "Alejandro Palacio", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Impredecible%20(Alejandro%20Palacio)%20-%20Alejandro%20Palacio%20-%202006.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v26", title: "LO QUE QUIERAS DE MI", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/LO%20QUE%20QUIERAS%20DE%20MI%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201995.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v27", title: "LOCAMENTE ENAMORADO", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/LOCAMENTE%20ENAMORADO%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201995.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v28", title: "Lejos de ti", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Lejos%20de%20ti%20-%20Binomio%20De%20Oro%20De%20America%20-%201998.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v29", title: "MANANTIAL DE AMOR", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/MANANTIAL%20DE%20AMOR%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201997.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v30", title: "ME VOY DE TI", artist: "BINOMIO DE ORO DE AMERICA, CANTA JORGE CELEDON", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/ME%20VOY%20DE%20TI%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%2C%20CANTA%20JORGE%20CELEDON%20-%201996.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v31", title: "Mas cerca de ti", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Mas%20cerca%20de%20ti%20-%20Binomio%20De%20Oro%20De%20America%20-%202000.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v32", title: "Me ilusione", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Me%20ilusione%20-%20Binomio%20De%20Oro%20De%20America%20-%202000.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v33", title: "Me sobran las palabras", artist: "Binomio De Oro De America, Canta Duban Bayona", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Me%20sobran%20las%20palabras%20-%20Binomio%20De%20Oro%20De%20America%2C%20Canta%20Duban%20Bayona%20-%202008.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v34", title: "Me vas a extrañar", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Me%20vas%20a%20extra%C3%B1ar%20-%20Binomio%20De%20Oro%20De%20America%20-%201999.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v35", title: "Mi segunda vida", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Mi%20segunda%20vida%20-%20Binomio%20De%20Oro%20De%20America%20-%202001.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v36", title: "Mis hojas secas", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Mis%20hojas%20secas%20-%20Binomio%20De%20Oro%20De%20America%20-%201997.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v37", title: "NO ME VUELVO A ILUSIONAR", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/NO%20ME%20VUELVO%20A%20ILUSIONAR%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201999.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v38", title: "NO PUDE OLVIDARTE", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/NO%20PUDE%20OLVIDARTE%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201998.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v39", title: "NO TE QUIERO PERDER", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/NO%20TE%20QUIERO%20PERDER%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201997.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v40", title: "NO TE VAYAS", artist: "BINOMIO DE ORO DE AMERICA, Canta JEAN CARLOS C. (Jorge Valbu", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/NO%20TE%20VAYAS%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%2C%20Canta%20JEAN%20CARLOS%20C.%20(Jorge%20Valbuena)%201993.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v41", title: "No me resignare", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/No%20me%20resignare%20-%20Binomio%20De%20Oro%20De%20America%20-%202001.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v42", title: "No puedo olvidarla", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/No%20puedo%20olvidarla%20-%20Binomio%20De%20Oro%20De%20America%20-%202001.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v43", title: "OLVIDALA", artist: "BINOMIO DE ORO DE AMERICA", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/OLVIDALA%20-%20BINOMIO%20DE%20ORO%20DE%20AMERICA%20-%201998.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v44", title: "Pa que me des tus besos", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Pa%20que%20me%20des%20tus%20besos%20-%20Binomio%20De%20Oro%20De%20America%20-%201998.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v45", title: "Parrandita parrandon", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Parrandita%20parrandon%20-%20Binomio%20De%20Oro%20De%20America%20-%201998.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v46", title: "Que bonito", artist: "Binomio de Oro de America, Canta Gaby Garcia", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Que%20bonito%20-%20Binomio%20de%20Oro%20de%20America%2C%20Canta%20Gaby%20Garcia%20-%201993.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v47", title: "Que dios permita este milagro", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Que%20dios%20permita%20este%20milagro%20-%20Binomio%20De%20Oro%20De%20America%20-%201995.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v48", title: "Quiero estar Contigo (Jose A. Moya)", artist: "Binomio de Oro de America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Quiero%20estar%20Contigo%20(Jose%20A.%20Moya)%20-%20Binomio%20de%20Oro%20de%20America%20-%202003.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v49", title: "Quiero que seas mi estrella", artist: "Binomio De Oro De America", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/Quiero%20que%20seas%20mi%20estrella%20-%20Binomio%20De%20Oro%20De%20America%20-%201999.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "v50", title: "RECORRIENDO A COLOMBIA", artist: "MIGUEL MORALES (Israel Romero) 1993", genre: "Vallenato",
    mp3Url: "https://archive.org/download/vallenato-binomio-de-oro-de-america/RECORRIENDO%20A%20COLOMBIA%20-%20MIGUEL%20MORALES%20(Israel%20Romero)%201993.mp3",
    cover: "https://archive.org/services/img/vallenato-binomio-de-oro-de-america" },
  { id: "m01", title: "TE QUIERO, TE QUIERO", artist: "JOSSIE ESTEBAN Y LA PATRULLA 15", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/001.TE%20QUIERO%2C%20TE%20QUIERO-%20JOSSIE%20ESTEBAN%20Y%20LA%20PATRULLA%2015%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m02", title: "TUTARAMACARA", artist: "LISANDRO MEZA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/002.TUTARAMACARA-%20LISANDRO%20MEZA%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m03", title: "EL AGUARDIENTERO", artist: "GRUPO PLUMA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/003.EL%20AGUARDIENTERO-%20GRUPO%20PLUMA%20(1990).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m04", title: "LA CELOSA", artist: "LOS SONORS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/004.LA%20CELOSA-%20LOS%20SONORS%20(1980).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m05", title: "AGUA QUE NO HAS DE BEBER", artist: "PASTOR LOPEZ Y SU COMBO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/005.AGUA%20QUE%20NO%20HAS%20DE%20BEBER-%20PASTOR%20LOPEZ%20Y%20SU%20COMBO%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m06", title: "POR UNA MALA MUJER", artist: "LOS LIDERES", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/006.POR%20UNA%20MALA%20MUJER-LOS%20LIDERES(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m07", title: "GUIAME", artist: "CUCO VALOY Y SU ORQUESTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/007.GUIAME-CUCO%20VALOY%20Y%20SU%20ORQUESTA%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m08", title: "PIENSA EN MI", artist: "EL CHECO ACOSTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/008.PIENSA%20EN%20MI-%20EL%20CHECO%20ACOSTA%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m09", title: "ALEGRIA Y AMOR", artist: "DANIDOM", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/009.ALEGRIA%20Y%20AMOR-%20DANIDOM%20(2003).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m10", title: "ADIOS MI VIDA", artist: "PALO SANTO Y SU GRUPO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/010.ADIOS%20MI%20VIDA-%20PALO%20SANTO%20Y%20SU%20GRUPO%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m11", title: "LA NEGRA SABROSA", artist: "MEDARDO Y SUS PLAYERS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/011.LA%20NEGRA%20SABROSA-%20MEDARDO%20Y%20SUS%20PLAYERS%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m12", title: "LA META DEL VAGO", artist: "POCHY Y SU COCOBAND", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/012.LA%20META%20DEL%20VAGO-POCHY%20Y%20SU%20COCOBAND%20(1990).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m13", title: "DEJAME ABRAZARTE", artist: "LOS FANTASMAS DEL CARIBE", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/013.DEJAME%20ABRAZARTE-%20LOS%20FANTASMAS%20DEL%20CARIBE%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m14", title: "POR ELLA", artist: "GRUPO CONTRASTE", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/014.POR%20ELLA-%20GRUPO%20CONTRASTE%20(1986).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m15", title: "DONDE ANDARA", artist: "SONORA DINAMITA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/015.DONDE%20ANDARA-%20SONORA%20DINAMITA%20(1987).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m16", title: "COMPRENDEME", artist: "LOS HERMANOS ROSARIO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/016.COMPRENDEME-LOS%20HERMANOS%20ROSARIO%20(1991).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m17", title: "COMPADRE QUERIDO", artist: "LA DIMENSION LATINA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/017.COMPADRE%20QUERIDO-%20LA%20DIMENSION%20LATINA%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m18", title: "LA HOJA DE TABACO", artist: "FRUKO Y SUS TESOS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/018.LA%20HOJA%20DE%20TABACO-%20FRUKO%20Y%20SUS%20TESOS%20(1987).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m19", title: "EL DIVORCIO", artist: "PALO SANTO Y SU GRUPO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/019.EL%20DIVORCIO-PALO%20SANTO%20Y%20SU%20GRUPO%20(1986).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m20", title: "A MILLON", artist: "WILFRIDO VARGAS Y SU ORQUESTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/020.A%20MILLON-%20WILFRIDO%20VARGAS%20Y%20SU%20ORQUESTA%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m21", title: "VIDA VACIA", artist: "LOS NUMERO UNO DE COLOMBIA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/021.VIDA%20VACIA-%20LOS%20NUMERO%20UNO%20DE%20COLOMBIA%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m22", title: "UN LUGAR PARA AMAR", artist: "CLAN CARIBE", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/022.UN%20LUGAR%20PARA%20AMAR-%20CLAN%20CARIBE%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m23", title: "EL CABALLITO", artist: "CAT BLUE", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/023.EL%20CABALLITO-%20CAT%20BLUE%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m24", title: "MOSAICO MANO A MANO", artist: "RODOLFO Y GUSTAVO QUINTERO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/024.MOSAICO%20MANO%20A%20MANO-%20RODOLFO%20Y%20GUSTAVO%20QUINTERO%20(1984).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m25", title: "YO SOY TU PAPA", artist: "ANTILLIAN BROTHERS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/025.YO%20SOY%20TU%20PAPA%20-ANTILLIAN%20BROTHERS%20(1990).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m26", title: "MELANCOLIA", artist: "PALO SANTO Y SU GRUPO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/026.MELANCOLIA-%20PALO%20SANTO%20Y%20SU%20GRUPO%20(1992).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m27", title: "LA NEGRA TOMASA", artist: "AFROSOUND", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/027.LA%20NEGRA%20TOMASA-AFROSOUND%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m28", title: "DECIDETE PRONTO", artist: "EL COMBO DE LAS ESTRELLAS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/028.DECIDETE%20PRONTO-%20EL%20COMBO%20DE%20LAS%20ESTRELLAS%20(1979).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m29", title: "TU CUCU", artist: "SONORA DINAMITA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/029.TU%20CUCU-%20SONORA%20DINAMITA%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m30", title: "ABISMO", artist: "ALCIDES DIAZ Y SU CONUNTO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/030.ABISMO-%20ALCIDES%20DIAZ%20Y%20SU%20CONUNTO%20(1992).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m31", title: "CRUELDAD", artist: "FABIAN Y HERNAN", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/031.CRUELDAD-%20FABIAN%20Y%20HERNAN%20(1987).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m32", title: "JOHANA", artist: "PABLO ATUESTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/032.JOHANA-PABLO%20ATUESTA%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m33", title: "LA NEGRA (Rmx)", artist: "JOSSIE ESTEBAN Y LA PATRULLA 15", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/033.LA%20NEGRA%20(Rmx)-JOSSIE%20ESTEBAN%20Y%20LA%20PATRULLA%2015%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m34", title: "EL RELAJO", artist: "JULIAN Y SU COMBO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/034.EL%20RELAJO-%20JULIAN%20Y%20SU%20COMBO%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m35", title: "AZUQUITA MAMI", artist: "LOS DEL INGENIO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/035.AZUQUITA%20MAMI-%20LOS%20DEL%20INGENIO%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m36", title: "MARINA MARINERA", artist: "FRUKO Y SUS TESOS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/036.MARINA%20MARINERA-%20FRUKO%20Y%20SUS%20TESOS%20(1989).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m37", title: "PRIMER AMOR", artist: "COMBO PALACIO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/037.PRIMER%20AMOR-%20COMBO%20PALACIO%20(1980).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m38", title: "CASARME NO", artist: "DON MEDARDO Y SUS PLAYERS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/038.CASARME%20NO-%20DON%20MEDARDO%20Y%20SUS%20PLAYERS%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m39", title: "DAME AMOR", artist: "HUGO MOLINARES Y SU ORQUESTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/039.DAME%20AMOR-HUGO%20MOLINARES%20Y%20SU%20ORQUESTA%20(1990).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m40", title: "CUANDO LLEGASTE TU", artist: "GRUPO FANTASMA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/040.CUANDO%20LLEGASTE%20TU%20-GRUPO%20FANTASMA%20(1888).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m41", title: "ESA MUJER", artist: "OSCAR D' LEON", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/041.ESA%20MUJER-%20OSCAR%20D'%20LEON%20(1984).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m42", title: "ENCADENADO", artist: "LA SONORA REAL", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/042.ENCADENADO-LA%20SONORA%20REAL%20(1985).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m43", title: "AMARILIS", artist: "CUCO VALOY Y SU ORQUESTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/043.AMARILIS-%20CUCO%20VALOY%20Y%20SU%20ORQUESTA%20(1986).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m44", title: "NUESTRO ANILLITO", artist: "LUIS SARMIENTO Y SU ORQUESTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/044.NUESTRO%20ANILLITO-%20LUIS%20SARMIENTO%20Y%20SU%20ORQUESTA%20(1980).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m45", title: "MUÑECA DE LOZA", artist: "GRUPO KALIMA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/045.MU%C3%91ECA%20DE%20LOZA-%20GRUPO%20KALIMA%20(1990).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m46", title: "QUE SE LARGUE PA' LA PORRA", artist: "LOS LATINOS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/046.QUE%20SE%20LARGUE%20PA'%20LA%20PORRA-LOS%20LATINOS%20(1983).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m47", title: "LA INGRATA", artist: "HUGO MOLINARES Y SU ORQUESTA", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/047.LA%20INGRATA-%20HUGO%20MOLINARES%20Y%20SU%20ORQUESTA%20(1990).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m48", title: "SEÑORA", artist: "RAUL MARRERO", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/048.SE%C3%91ORA-%20RAUL%20MARRERO%20(1988).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m49", title: "LLORARAS", artist: "SUPER COMBO VERACRUZ", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/049.LLORARAS-%20SUPER%20COMBO%20VERACRUZ%20(1985).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" },
  { id: "m50", title: "AL OTRO LADO DEL RIO", artist: "LOS TRAVOLTOSOS", genre: "Merengue",
    mp3Url: "https://archive.org/download/aguja-y-vinilo-vol.1-parte-1_202210/050.AL%20OTRO%20LADO%20DEL%20RIO-%20LOS%20TRAVOLTOSOS%20(1982).mp3",
    cover: "https://archive.org/services/img/aguja-y-vinilo-vol.1-parte-1_202210" }
];
